### ISSUE TITLE
Connection failure when listening on multiple interfaces and overriding host candidate

### ISSUE THREAD

**Issue by streamer45** [pion/ice#541]
I admit I am not sure if this is the intended behaviour but since `MultiUDPMuxDefault` was introduced we had to change the way we were listening on multiple interfaces to make things work as before. So now we are passing multiple `UDPMuxDefault`, one per network interface/address. However, there's an issue when having multiple interfaces and at the same time overriding the host candidate through `SetNAT1To1IPs()`.

The agent is generating the same candidate pair and any successive connection get essentially discarded in here:

https://github.com/pion/ice/blob/daacdc3598ea82ac317c2e91a15db4211349cc16/agent.go#L829-L836

This results in only the first address to be considered which can easily lead to failure (e.g. if it's the loopback device). 

I am wondering if it would be feasible to have the same candidate served by potentially more than one connection/address behind at the same time, or at least until one of them actually succeeds in connecting.

@cnderrauber I understand you have been working on this kind of logic lately, wondering if you had any thoughts on this one.

**Comment by cnderrauber** [comment]
If you have multiple interfaces to listen on,  don't use a single external address to call SetNAT1To1IPs, which override your candidates. And it will cause another port conflict issue like this: 

You have interface IA, IB, both mapping to IC. Two clients 1 and 2.
client 1 get server candidates IC:34567(from IA), IC:45678(from IB)
client 2 get server candidates IC:34567(from IB), IC:45678(from IA), because when pion allocates port for client2, IA:45678 and IB:34567 are free to use, but when they mapped to IC, will conflict with client1's address and failed to connect.

The better way is (what we are doing now):
1. enumerate the interfaces you are going to use. (IA, IB, IC)
2. resolve external address for each interface (by public stun server) (IA -> EA, IB ->EB, IC -> EA)
3. SetNAT1To1IPs with mapping pair instead of a single external address, and if you have two interface resolved to same public address, only map the first one and keep the other one map to itself. SetNAT1To1IPs([]string{EA/IA, EB/IB, IC/IC})

**Comment by streamer45** [comment]
@cnderrauber That "trick" seems to work nicely. Out of curiosity, would it be acceptable to map the first interface (e.g. IA) as EA/IA and any subsequent interface to itself (IB/IB, IC/IC, and so on)? I am thinking of a scenario where resolving the external address is not possible (e.g. blocked outgoing ports) and the user will explicitly provide a single public IP instead.

**Comment by cnderrauber** [comment]
@streamer45 It will definitely work if your IA can be accessed from EA by public clients.

**Comment by streamer45** [comment]
Very well, this was extremely helpful, thank you again. We can close this one :)
