### ISSUE TITLE
Make srflx gathering configurable

### ISSUE THREAD

**Issue by Sean-Der** [pion/ice#58]
@masterada @trivigy 

We need to make `srflx` gathering only do the 'default' interface by default I think. 

While not spec-compliant I have gotten feedback from multiple people about speed regressions. This wouldn't be a problem if we had Trickle ICE from day one, but lots of people have setup their signaling already.

I say we make configurable, and maybe when we do `/v3` we can roll back to the 'all interface' behavior.

**Comment by trivigy** [comment]
I propose to introduce a `DefaultOnly` policy and `FullSrflx` policy. Don't care about the naming. This way it will also allow us to continue testing and improving the speed of complete server reflexive gathering while there is a standard default-only functionality to address speed issues for the immediate future.

**Comment by masterada** [comment]
Is this still an issue after https://github.com/pion/ice/pull/56?

Or maybe gather only the default if trickle is false - if some needs all, they should implement trickle (one less config to deprecate in v3 :) )

**Comment by trivigy** [comment]
@masterada it is still a significant issue on my end. I cannot run any of my unittests because of how long it takes to establish each connection. My p2p library has a significant churn of establishing and dropping connections. This `collect all` really impacts it, especially since due to BUNDLE really only the primary candidates ends up being used anyway.

**Comment by masterada** [comment]
@trivigy What does slow mean? Is it over 5 seconds? How fast do we want this? Asking because if its over 5 seconds there should still be something slowing it down. If its 5 seconds maybe we can decrease the timeout to 2/3 seconds in https://github.com/pion/ice/blob/a58a281d3a851399f491db2f8815917ea6f46d68/gather.go#L233

Or we could also use different timeout for trickle/non-trickle. Im not against collecting only from primary interface, just looking at alternatives for the full picture :)

**Comment by trivigy** [comment]
@masterada I am with you on making sure to address everyone's concerns. That is why my proposal was to simply add a special type policy. In general I don't have the same issue with chromium which does trickle. I should spend the time and fine the code in the chromium source to see exactly what they are doing but it is much much faster than pion.

In terms of speed, and since I made the it parallel gathering, it is exactly 5s. A simple unittest I have that does 1:1 establishment takes 10.3s. Which means it spends 5s per each connection startup. That is a crazy amount of time. With the old "default only" functionality it took 0.06s. Even if we decrease the timeout to 1s, it will still take about 2s for a simple tests. Those are really not production speeds.

I think the only way to address this is to create a special time policy for now until we keep improving the ice process to equal the chromium performance. Then we can remove it all together.

**Comment by masterada** [comment]
I see, thanks for the details. That really is a big difference :)

For the tests i suggest you check out these (it wont help in general, but might help you) 
vnet: https://github.com/pion/transport/issues/13
dummy stun server: (need to find the link, writing from mobile :D )
