### ISSUE TITLE
Convert a.run() to a proper synchronization system

### ISSUE THREAD

**Issue by trivigy** [pion/ice#67]
## Summary
There is a real contention point with how the current synchronization is implemented. `a.run()` creates a single worker queue in order to do "pseudo locking" and to synchronize execution inside of the ice library. Unfortunately this is a really challenging design and creates a lot of issues. E.g. Bad perf benchmark, pool locking capabilities.

It would be nice to change this to improve performance and synchronization issues.

## Describe alternatives you've considered
Did not consider any alternatives but the best solution would be something that does not require locking at all. Here is one really good place to draw ideas from:
https://drive.google.com/file/d/1nPdvhB0PutEJzdCq5ms6UI58dp50fcAN/view

**Comment by Sean-Der** [comment]
I have cleaned this up a bit, and now `pion/ice` isn't in the top 25. I am not going to work on this further.

I didn't end up removing `.run`, it is more then simple mutual exclusion it also allows cancellation of queued locks. I tried replacing things with a simple mutex, but ended up being more messy then I thought it would be.

For the cases where we want to return values from `.run` I have updated things to use atomics (instead of channels). `.run` itself is now blocking, and doesn't push the task across the channel. It instead calls the function directly.
